#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}"

INSTALL_PETSC=0
SKIP_SYSTEM_DEPS=0
USE_VENV=1
UPGRADE_PIP=0
INSTALL_SHELL_HOOK=0
PETSC_VERSION="3.20.3"
PETSC_PREFIX="${HOME}/software"
PETSC_ARCH="arch-linux-c-debug"
PYTHON_BIN=""
VENV_DIR="${REPO_ROOT}/.picurv-venv"
SHELL_RC="${HOME}/.bashrc"

usage() {
  cat <<'EOF'
Usage: bootstrap_install.sh [options]

Automates local PICurv setup:
1) installs base system dependencies (Debian/Ubuntu),
2) creates a managed Python virtual environment by default,
3) optionally installs PETSc with DMSwarm,
4) verifies PETSc + DMSwarm visibility,
5) builds PICurv binaries.

Options:
  --install-petsc            Build/install PETSc from source.
  --petsc-version <ver>      PETSc version tag (default: 3.20.3).
  --petsc-prefix <dir>       Parent directory for PETSc source/build.
  --petsc-arch <arch>        PETSc arch name (default: arch-linux-c-debug).
  --python-bin <path>        Python interpreter to seed the venv or use directly.
  --venv-dir <dir>           Managed venv path (default: .picurv-venv).
  --no-venv                  Use the selected Python directly.
  --with-plotting            Compatibility option; matplotlib is installed by default.
  --upgrade-pip              Upgrade pip before installing Python dependencies.
  --install-shell-hook       Add an idempotent source line to ~/.bashrc.
  --shell-rc <path>          Shell startup file for --install-shell-hook.
  --skip-system-deps         Skip apt package installation.
  -h, --help                 Show this help.

Examples:
  ./bootstrap_install.sh
  ./bootstrap_install.sh --install-petsc
  ./bootstrap_install.sh --install-shell-hook
  ./bootstrap_install.sh --no-venv
EOF
}

log() {
  printf '[INFO] %s\n' "$*"
}

die() {
  printf '[ERROR] %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command '$1' is missing."
}

absolute_path() {
  local path="$1"
  if [[ "${path}" = /* ]]; then
    printf '%s\n' "${path}"
  else
    printf '%s/%s\n' "${REPO_ROOT}" "${path}"
  fi
}

python_version_label() {
  "$1" -c 'import sys; print(".".join(str(part) for part in sys.version_info[:3]))'
}

python_is_supported_seed() {
  "$1" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)'
}

verify_python_dependencies() {
  local python_bin="$1"

  log "Verifying PICurv Python dependencies in isolated launcher mode..."
  if ! env -u PYTHONPATH PYTHONNOUSERSITE=1 "${python_bin}" -c 'import yaml, numpy, packaging, matplotlib'; then
    die "PICurv Python dependency verification failed. Repair the isolated environment with: env -u PYTHONPATH PYTHONNOUSERSITE=1 ${python_bin} -m pip install --no-cache-dir --force-reinstall pyyaml numpy packaging matplotlib"
  fi
}

python_runtime_library_dirs() {
  local python_bin="$1"
  local resolved_python

  resolved_python="$(command -v "${python_bin}" || printf '%s' "${python_bin}")"
  "${python_bin}" - <<'PY'
import os
import sysconfig

for key in ("LIBDIR", "LIBPL"):
    value = sysconfig.get_config_var(key)
    if value and os.path.isdir(value):
        print(os.path.realpath(value))
PY
  if command -v ldd >/dev/null 2>&1 && [[ -x "${resolved_python}" ]]; then
    ldd "${resolved_python}" 2>/dev/null | awk '
      /=> \// { path = $3 }
      /^[[:space:]]*\// { path = $1 }
      path != "" {
        sub(/\/[^\/]+$/, "", path)
        print path
        path = ""
      }
    '
  fi
}

write_python_env_file() {
  local python_bin="$1"
  local env_file="${REPO_ROOT}/.picurv-python-env"
  local runtime_dirs

  runtime_dirs="$(
    python_runtime_library_dirs "${python_bin}" \
      | awk '$0 !~ "^/(lib|lib64|usr/lib|usr/lib64)(/|$)"' \
      | awk 'NF && !seen[$0]++' \
      | paste -sd ':' -
  )"
  {
    printf '# Generated by bootstrap_install.sh. Do not commit.\n'
    printf 'PICURV_PYTHON_LD_LIBRARY_PATH=%q\n' "${runtime_dirs}"
  } > "${env_file}"
}

install_shell_hook() {
  local rc_path="$1"
  local hook_path="${REPO_ROOT}/etc/picurv.sh"
  local begin_marker="# >>> PICurv shell setup >>>"
  local end_marker="# <<< PICurv shell setup <<<"
  local tmp_path

  mkdir -p "$(dirname "${rc_path}")"
  touch "${rc_path}"
  tmp_path="$(mktemp "${rc_path}.picurv.XXXXXX")"
  awk -v begin="${begin_marker}" -v end="${end_marker}" '
    $0 == begin {skip = 1; next}
    $0 == end {skip = 0; next}
    skip != 1 {print}
  ' "${rc_path}" > "${tmp_path}"
  {
    printf '%s\n' "${begin_marker}"
    printf 'source %q\n' "${hook_path}"
    printf '%s\n' "${end_marker}"
  } >> "${tmp_path}"
  mv "${tmp_path}" "${rc_path}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install-petsc) INSTALL_PETSC=1; shift ;;
    --skip-system-deps) SKIP_SYSTEM_DEPS=1; shift ;;
    --petsc-version) PETSC_VERSION="${2:?missing value for --petsc-version}"; shift 2 ;;
    --petsc-prefix) PETSC_PREFIX="${2:?missing value for --petsc-prefix}"; shift 2 ;;
    --petsc-arch) PETSC_ARCH="${2:?missing value for --petsc-arch}"; shift 2 ;;
    --python-bin) PYTHON_BIN="${2:?missing value for --python-bin}"; shift 2 ;;
    --venv-dir) VENV_DIR="$(absolute_path "${2:?missing value for --venv-dir}")"; shift 2 ;;
    --no-venv) USE_VENV=0; shift ;;
    --with-plotting) shift ;;
    --upgrade-pip) UPGRADE_PIP=1; shift ;;
    --install-shell-hook) INSTALL_SHELL_HOOK=1; shift ;;
    --shell-rc) SHELL_RC="$(absolute_path "${2:?missing value for --shell-rc}")"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

if [[ -z "${PYTHON_BIN}" ]]; then
  if command -v python3.12 >/dev/null 2>&1; then
    PYTHON_BIN="python3.12"
  elif command -v python3.11 >/dev/null 2>&1; then
    PYTHON_BIN="python3.11"
  elif command -v python3.10 >/dev/null 2>&1; then
    PYTHON_BIN="python3.10"
  else
    PYTHON_BIN="python3"
  fi
fi

require_cmd "${PYTHON_BIN}"
require_cmd git

if [[ "${SKIP_SYSTEM_DEPS}" -eq 0 ]]; then
  require_cmd apt-get
  log "Installing base system dependencies (Debian/Ubuntu)..."
  sudo apt-get update
  sudo apt-get install -y \
    build-essential gfortran mpich git make pkg-config \
    libx11-dev python3 python3-pip python3-venv
fi

PYTHON_VERSION="$(python_version_label "${PYTHON_BIN}")"
log "Selected Python seed: ${PYTHON_BIN} (${PYTHON_VERSION})"

if [[ "${USE_VENV}" -eq 1 ]]; then
  if ! python_is_supported_seed "${PYTHON_BIN}"; then
    die "Managed venv installs require Python 3.10+; selected ${PYTHON_BIN} is ${PYTHON_VERSION}. Load a newer Python module, pass --python-bin, or use --no-venv."
  fi
  log "Creating/updating managed Python environment at ${VENV_DIR}..."
  "${PYTHON_BIN}" -m venv "${VENV_DIR}"
  CLI_PYTHON="${VENV_DIR}/bin/python"
  if [[ "${UPGRADE_PIP}" -eq 1 ]]; then
    log "Upgrading pip in managed Python environment..."
    env -u PYTHONPATH PYTHONNOUSERSITE=1 "${CLI_PYTHON}" -m pip install --upgrade pip
  fi
  PYTHON_PACKAGES=(pyyaml numpy packaging matplotlib)
  log "Installing Python dependencies into managed venv: ${PYTHON_PACKAGES[*]}"
  env -u PYTHONPATH PYTHONNOUSERSITE=1 "${CLI_PYTHON}" -m pip install "${PYTHON_PACKAGES[@]}"
else
  CLI_PYTHON="${PYTHON_BIN}"
  log "Installing Python dependencies with site-managed Python: ${CLI_PYTHON}"
  if [[ "${UPGRADE_PIP}" -eq 1 ]]; then
    log "Upgrading pip for site-managed Python..."
    "${CLI_PYTHON}" -m pip install --upgrade pip
  fi
  PYTHON_PACKAGES=(pyyaml numpy packaging matplotlib)
  "${CLI_PYTHON}" -m pip install "${PYTHON_PACKAGES[@]}"
fi

verify_python_dependencies "${CLI_PYTHON}"

printf '%s\n' "$(command -v "${CLI_PYTHON}" || printf '%s' "${CLI_PYTHON}")" > "${REPO_ROOT}/.picurv-python"
write_python_env_file "${CLI_PYTHON}"

if [[ "${INSTALL_PETSC}" -eq 1 ]]; then
  require_cmd mpicc
  PETSC_SRC="${PETSC_PREFIX}/petsc-${PETSC_VERSION}"
  mkdir -p "${PETSC_PREFIX}"

  if [[ ! -d "${PETSC_SRC}" ]]; then
    log "Cloning PETSc v${PETSC_VERSION} into ${PETSC_SRC}..."
    git clone -b "v${PETSC_VERSION}" https://gitlab.com/petsc/petsc.git "${PETSC_SRC}"
  else
    log "Using existing PETSc source at ${PETSC_SRC}."
  fi

  log "Configuring PETSc with DMSwarm support..."
  pushd "${PETSC_SRC}" >/dev/null
  ./configure --PETSC_ARCH="${PETSC_ARCH}" \
              --with-cc=mpicc --with-cxx=mpicxx --with-fc=mpif90 \
              --download-fblaslapack --download-metis --download-parmetis \
              --with-dmswarm=1 --with-debugging=1
  make all
  make check
  popd >/dev/null

  export PETSC_DIR="${PETSC_SRC}"
  export PETSC_ARCH="${PETSC_ARCH}"
fi

if [[ -z "${PETSC_DIR:-}" ]]; then
  die "PETSC_DIR must be set (or use --install-petsc)."
fi

PETSC_DMSWARM_HEADER="${PETSC_DIR}/include/petscdmswarm.h"
PETSC_CONF_CANDIDATES=("${PETSC_DIR}/include/petscconf.h")
if [[ -n "${PETSC_ARCH:-}" ]]; then
  PETSC_CONF_CANDIDATES=("${PETSC_DIR}/${PETSC_ARCH}/include/petscconf.h" "${PETSC_CONF_CANDIDATES[@]}")
fi
PETSC_CONF=""
for candidate in "${PETSC_CONF_CANDIDATES[@]}"; do
  if [[ -f "${candidate}" ]]; then
    PETSC_CONF="${candidate}"
    break
  fi
done
[[ -n "${PETSC_CONF}" ]] || die "PETSc config not found. Checked: ${PETSC_CONF_CANDIDATES[*]}"
[[ -f "${PETSC_DMSWARM_HEADER}" ]] || die "DMSwarm header not found: ${PETSC_DMSWARM_HEADER}"

log "Verified PETSc config (${PETSC_CONF}) and DMSwarm header."

log "Building PICurv binaries..."
cd "${REPO_ROOT}"
"${CLI_PYTHON}" ./picurv_cli/picurv build

[[ -x "${REPO_ROOT}/bin/simulator" ]] || die "Missing binary: bin/simulator"
[[ -x "${REPO_ROOT}/bin/postprocessor" ]] || die "Missing binary: bin/postprocessor"
[[ -x "${REPO_ROOT}/bin/picurv" ]] || die "Missing binary: bin/picurv"

log "Bootstrap complete."
log "PICurv Python: ${CLI_PYTHON}"
if [[ "${INSTALL_SHELL_HOOK}" -eq 1 ]]; then
  install_shell_hook "${SHELL_RC}"
  log "Installed PICurv shell hook in ${SHELL_RC}."
  log "Reload with: source ${SHELL_RC}"
else
  log "To add picurv to your PATH, run:"
  log "  echo 'source ${REPO_ROOT}/etc/picurv.sh' >> ~/.bashrc && source ~/.bashrc"
  log "Or rerun bootstrap with: --install-shell-hook"
fi
log "Then verify with: picurv --help"
